name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install OpenSSH server
      - name: Install OpenSSH server
        run: sudo apt update && sudo apt install openssh-server -y

      # Start SSH service
      - name: Start SSH service
        run: sudo systemctl start ssh

      # Check SSH service status
      - name: Check SSH service status
        run: systemctl status ssh
