name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setting the environment up.
      env:
        VNC_USER_PASSWORD: ${{ secrets.SSH_PASSWD }}
        VNC_PASSWORD: ${{ secrets.SSH_PASSWD }}
      run: source configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD"

