name: macOS SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Install OpenSSH server
      - name: Install OpenSSH server
        run: sudo systemsetup -setremotelogin on

      # Set up SSH connection
      - name: Set up SSH connection
        run: |
          sudo dscl . -passwd /Users/root "${{ secrets.SSH_PASSWD }}"
          sudo sed -i '' 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
          sudo launchctl load /System/Library/LaunchDaemons/ssh.plist

      # Check SSH service status
      - name: Check SSH service status
        run: sudo systemsetup -getremotelogin

      # Install frpc
      - name: Install frpc
        run: |
          wget -O frp_darwin_amd64.tar.gz https://github.com/fatedier/frp/releases/latest/download/frp_0.52.3_darwin_amd64.tar.gz
          tar -xzf frp_darwin_amd64.tar.gz
          mv frp_*_darwin_amd64 frp_darwin_amd64
          sudo mv frp_darwin_amd64/frpc /usr/local/bin/
          rm -rf frp_darwin_amd64*

      # Configure frpc
      - name: Configure frpc
        run: |
          echo "[common]" > frpc.ini
          echo "server_addr = ${{ secrets.FRPC_SERVER_ADDR }}" >> frpc.ini
          echo "server_port = ${{ secrets.FRPC_SERVER_PORT }}" >> frpc.ini
          echo "token = ${{ secrets.FRPC_TOKEN }}" >> frpc.ini
          echo "[ssh]" >> frpc.ini
          echo "type = tcp" >> frpc.ini
          echo "local_ip = 127.0.0.1" >> frpc.ini
          echo "local_port = 22" >> frpc.ini
          echo "remote_port = 6002" >> frpc.ini

      # Start frpc
      - name: Start frpc
        run: sudo frpc -c frpc.ini

      - name: Don't kill instance
        if: ${{ failure() }}
        run: sleep 1h # Prevent killing the instance after failure
